#AWSTemplateFormatVersion: "2010-09-09"
#Description: "Create DB Users via workflow"
Parameters:
  TargetId:
    Type: String
  MasterArn:
    Type: String
  DbInstanceIdentifier:
    Type: String
Resources:
  SplunkUserSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "/db-credential/${DbInstanceIdentifier}/SPLUNK_USER"
      GenerateSecretString:
        ExcludeCharacters: '@~=/}][{'
        RequireEachIncludedType: True
        PasswordLength: 15
        GenerateStringKey: "password"
        SecretStringTemplate: !Sub '{"username": "SPLUNK_USER","master_arn":"${MasterArn}"}'
    Tags:
      - Key: RDSbackup
        Value: "true"
  #SplunkUserTargetAttachment:
   # Type: AWS::SecretsManager::SecretTargetAttachment
    #Properties:
     # SecretId: !Ref SplunkUserSecret
      #TargetType: AWS::RDS::DBInstance
      #TargetId: !Ref TargetId

  #SplunkUserCreation:
   # DependsOn: 
    #  - SplunkUserTargetAttachment
    #Type: Custom::CreateUser
    #Properties:
     # ServiceToken: !Sub '{{resolve:ssm:oracleUserCreation}}'
     # SecretArn: !Ref SplunkUserSecret
